#! /bin/bash

###INSTALL###

if [ -e src/pass ]; then
    chmod a-rwx "$0"
    if [ ! -e /usr/bin/shc ]; then
        sudo apt -y install -y shc -y
    fi
    shc -f "$0" -o "$0"
    chmod u-w "$0"
    rm "$0".x.c
    cp .Azer /etc/
    mkdir /etc/.raulm
    mkdir /etc/.raulm/.Ye
    chmod a-rwx /etc/.raulm
    chmod u-w /etc/.raulm
    mkdir /var/.Hj
    chmod a-rwx /var/.Hj
    chmod u-w /var/.Hj
    mkdir /usr/local/.Ko
    chmod a-rwx /usr/local/.ko
    chmod u-w /usr/local/.ko
    cp src/pass /usr/bin
fi

#######

check() {
    if [ "${pass}" != "$(head -22 /etc/.Azer | python3)"; then
        echo -e "\e[1;31mWrong"
        exit
}

if [ "$(basename "$0")" = "pass" ] && [ -z "$1" ]; then
    echo -e "\e[1mUsage:\e[0m pass [argument][file1][file2]...\n\nNo argument:\t\t\tSecure files or one file by password\n-r --remove:\t\t\t\tRemove security password from files\npass 'none':\t\t\t\tshow this help message\n\n\e[1mFor secured files:\nUsage:\e[0m [file][argument]\n\n-c --change:\t\t\t\tChange password\nNone:\t\t\t\tstart file with password\n\n\e[1me.g:\e[0m -c argument will not work in secured file so try to change it or use another one"
elif [ "$(basename "$0")" != "pass" ] && [[ "$1" = !(-c|--change) ]]; then
    read -rsp "Enter password: " pass
    check
    echo
elif [ "$(basename "$0")" != "pass" ] && [[ "$1" =~ ^(-c|--change) ]]; then
    read -rsp "Enter current password: " pass
    check
    sed -i "/$(basename "$0"):/d" /usr/local/.Ko/.Yeiv /var/.Hj/.Yerws
    if trap '' SIGINT; then
        echo
        read -rsp "Change password: " pass
    fi
    head -9 /etc/.Azer | tail -10 | python3 
    echo -e "\n\e[1;32mpassword successfully updated"
    exit
elif [ "$(basename "$0")" = "pass" ] && [[ "$1" =~ ^(-r|--remove) ]]; then
    for arv in "${@:2}"; do
        if [[ "${arv}" =~ ^(-[a-z]|-[A-Z]|-[0-9]|--[a-z]|--[A-Z]|--[0-9]) ]]; then
            echo -e "\e[1mUnknown argument ${arv}\e[0m\n"
        elif [ ! -e "${arv}" ]; then
            echo -e "\e[1mUnfound\e[1m\n"
        elif ! grep "pass" "${arv}" >/dev/null; then
            echo -e "\e[1m$(basename "${arv}") already not secured\e[0m\n"
            chmod a-w "${arv}"
        elif grep "pass" "${arv}" >/dev/null; then
            read -rsp "Enter $(basename "${arv}") password: " pass
            echo
            head -22 Azer| python 3
            if [ "${pass}" != "$(head -22 /etc/.Azer | python3)" ]; then
                echo -e "\e[1;31mWrong"
                chmod a-w "${arv}"
                exit
            fi
            sed -i "2,4d" "${arv}"
            sed -i "/$(basename "${arv}"):/d" /var/.Hj/.Yerws /usr/local/.Ko/.Yeiv
            chmod a+rwx "${arv}"
            echo -e "\e[1;33m$(basename "${arv}") security desabled\e[\n0m\n"
            if [ ! -s /var/.Hj/.Yerws ] && [  ! -s /usr/local/.Ko/.Yeiv ]; then
                rm /var/.Hj/.Yerws /usr/local/.Ko/.Yeiv
            fi
        fi
    done
elif [ "$(basename "$0")" = "pass" ]; then
    for arg in "$@"; do
        if [[ "${arg}" =~ ^(-[a-z]|-[A-Z]|-[0-9]|--[a-z]|--[A-Z]|--[0-9]) ]]; then
            echo -e "\e[1mUnknown argument ${arv}\e[0m\n"
        elif [ ! -e "${arg}" ]; then
            echo -e "\e[1mUnfound\e[1m\n"
        elif grep "pass" "${arg}" >/dev/null; then
            echo -e "\e[1m$(basename "${arg}") already secured\e[0m\n"
            chmod a-w "${arg}"
        elif ! grep "pass" "${arg}" >/dev/null; then
            sed -i "2i\ \npass" "${arg}"
            if trap '' SIGINT; then
                read -rsp "Creat $(basename "${arg}") password: " pass
                echo
            fi
            head -9 /etc/.Azer | tail -10 | python3 
            chmod go-rwx "${arg}"
            chmod a-w "${arg}"
            echo -e "\e[1;32m$(basename "${arg}") password successfully created\e[\n0m\n"
        fi
    done
fi
